version: '2'

services:
  products:
    build: .
    command: bundle exec ruby products_service.rb
    ports:
      - "9292:9292"
    links:
      - mongodb
      - mongodb:mongodb.cloud66.local
    environment:
      - RAILS_ENV=production
      - RACK_ENV=production
  mongodb:
    image: mongo
